- name: get Glayson Olivieri dotfiles to ./files
  git:
    repo: 'https://github.com/g5olivieri/dotfiles.git'
    dest: ./files

- name: get base16 colors
  git: 
    repo: 'https://github.com/chriskempson/base16-shell.git'
    dest: ~/.config/base16-shell

- name: get vundle vim
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim

- name: copy vim configs from ./files to ~/ 
  copy:
    src: ./files/.vimrc
    dest: ~/.vimrc

- name: copy tmux configs from ./files to ~/ 
  copy:
    src: ./files/.tmux.conf
    dest: ~/.tmux.conf


- name: copy zsh configs from ./files to ~/ 
  copy:
    src: ./files/.zshrc
    dest: ~/.zshrc

- name: create docker group
  group:
    name: docker
    state: present 

- name: add user to docker group
  user: 
    append: True
    name: "{{ ansible_user }}"
    groups: docker
    shell: /bin/zsh

- name: get oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git' 
    dest: ~/.oh-my-zsh

- name: change default shell
  command: chsh -s /bin/zsh
