version: '3'

services: 
  app:
    build: .
    command: php -S 0.0.0.0:8080 -c php.ini
    depends_on:
      - db
    working_dir: /app
    ports:
      - 8080:8080
    volumes: 
    - .:/app

  db:
    image: mysql:alpine
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
