version: '3'

services: 
  app:
    build: .
    depends_on:
      - postgres
    working_dir: /app
    volumes: 
    - .:/app

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
